
packages:
  - "packages/*"

catalog:

  "esbuild": "^0.23.1"
  "crc": "^4.3.2"
  "typescript": "^5.5.4"
  "fast-glob": "^3.3.2"
  "smol-toml": "^1.3.0"
  "chokidar": "^3.6.0"
  "ansi-escapes": "^7.0.0"
  "kleur": "^4.1.5"

  "@types/node": "^22.5.2"

  "fs-extra": "^11.2.0"
  "@types/fs-extra": "^11.0.4"

  "qs": "^6.13.0"
  "@types/qs": "^6.9.15"

  "lodash-es": "^4.17.21"
  "@types/lodash-es": "^4.17.12"

  "prompts": "^2.4.2"
  "@types/prompts": "^2.4.9"

  "pg": "^8.12.0"
  "@types/pg": "^8.11.6"

  "knex": "^3.1.0"
  "extract-pg-schema": "^5.1.2"

catalogs:
  koa:
    "koa": "^2.15.3"
    "@types/koa": "^2.15.0"

    "@koa/router": "^12.0.1"
    "@types/koa__router": "^12.0.4"

    "koa-logger": "^3.2.1"
    "@types/koa-logger": "^3.1.5"

  solid:
    "solid-js": "^1.8.21"
    "@solidjs/router": "^0.14.3"

  vite:
    "vite": "^5.4.3"
    "vite-plugin-solid": "^2.10.2"

  zod:
    "zod": "^3.22.4"
    "zod-validation-error": "^3.0.3"
    "ts-to-zod": "^3.11.0"
