import { resolve, join } from "node:path";

import fsx from "fs-extra";
import glob from "fast-glob";
import { type BuildOptions, build as esbuild } from "esbuild";

import { defaults } from "@appril/dev";
import { renderToFile } from "@appril/dev-utils";

import type { ResolvedConfig } from "@/@types";

import template from "./templates/knexfile.hbs";

export const BANNER = `/**
* @generated by @appril/dbxt-migrate; do not modify manually!
*/`;

type MigrationsSourceFile = {
  path: string;
  const: string;
};

type MigrationsSourceRenderContext = ResolvedConfig & {
  defaults: Record<string, unknown>;
  files: Array<MigrationsSourceFile>;
};

export default async (
  // absolute path
  root: string,
  {
    // relative to root
    outdir,
    config,
    esbuildConfig,
  }: {
    config: ResolvedConfig;
    esbuildConfig: BuildOptions;
    outdir?: string;
  },
): Promise<string> => {
  const { migrationDir } = config;

  const matches = await glob("**/*.ts", {
    cwd: resolve(root, migrationDir),
    onlyFiles: true,
    absolute: false,
  });

  const files: Array<MigrationsSourceFile> = [];

  for (const path of matches) {
    files.push({
      path: path.replace(/\.ts$/, ""),
      const: ["$", path.replace(/\W/g, "_")].join(""),
    });
  }

  const knexfile = resolve(root, `knexfile.${new Date().getTime()}.ts`);

  await renderToFile<MigrationsSourceRenderContext>(
    knexfile,
    BANNER + template,
    {
      ...config,
      defaults,
      files: files.sort((a, b) => a.path.localeCompare(b.path)),
    },
  );

  const outfile = resolve(root, join(outdir || ".", "knexfile.mjs"));

  try {
    await esbuild({
      ...esbuildConfig,
      bundle: true,
      entryPoints: [knexfile],
      outfile,
      logLevel: "error",
    });
  } finally {
    await fsx.unlink(knexfile);
  }

  return outfile;
};
