import handlebars from "handlebars";

export const BANNER = `/**
* @generated by @appril/dev; do not modify manually!
*/`;

type Options = { format?: boolean };

export function render<Context = object>(
  template: string,
  context: Context,
  options?: Options,
): string {
  const content = handlebars.compile(template, { noEscape: true })(context);
  return options?.format ? content.replace(/^\s*[\r\n]/gm, "") : content;
}
