export * from "./types";

export const BANNER = `/**
* @generated by @appril/pgxt-cli; do not modify manually!
*/`;

export const tablesDir = "tables";
export const typesDir = "types";
export const enumsDir = "enums";
